[package]
name = "passman"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }
rpassword = "7.3.1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
thiserror = "2.0.11"
